version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3000'
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/tarot
        depends_on:
            - mongodb
        volumes:
            - ./public:/app/public
        networks:
            - app-network

    mongodb:
        image: mongo:latest
        ports:
            - '27018:27017'
        volumes:
            - mongodb_data:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongodb_data:
