version: '3.8'

services:
    tarot-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3000'
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/tarot
        depends_on:
            - mongodb
        volumes:
            - ./public:/app/public
        networks:
            - bot-network
        container_name: tarot-app

    mongodb:
        image: mongo:latest
        ports:
            - '27018:27017'
        volumes:
            - mongodb_data:/data/db
        networks:
            - bot-network

networks:
    bot-network:
        external: true

volumes:
    mongodb_data:
